name: Update README

on: [push]

jobs:
  build-update:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
        
    - name: Install pip
      run: python3 -m pip install --upgrade pip setuptools wheel
      
    - name: Install dependencies
      run: python3 -m pip install Pillow

    - name: Update README
      run: python3 .github/scripts/update_readme.py
